### ISSUE TITLE
Plugin no longer displaying w/l ratios

### ISSUE THREAD

**Issue by canuseeme** [mrmoss/saltybet_tools_chrome_extension#6]
Edit: It appears to be working again now, I guess the website it draws it's data from was temporarily offline.

**Comment by mrmoss** [comment]
I really need to migrate that service to another box.

It would also help if I was doing something semi smart like websockets
instead of doing the easiest thing possible and spamming connections with
an interval.

I have zero time to maintain this project - that being said, if anyone out
there implements websockets on the server side (
https://github.com/mrmoss/saltybet_tools) and on the extension side here,
I'd be more that willing to review pull requests and swap over the server
and upload a new extension.
