### ISSUE TITLE
https://salty.manly.parts/ 502 Bad Gateway

### ISSUE THREAD

**Issue by martnsh** [mrmoss/saltybet_tools_chrome_extension#8]
Not sure if this goes here, but I'll try anyway.
This shows up when trying to access the site.

502 Bad Gateway
nginx/1.10.0 (Ubuntu)

Doesn't seem to be a problem on my side, but I'm not too sure.
Version is 2017.6.1.0.

**Comment by martnsh** [comment]
Starts working right after I post this. Nice

**Comment by mrmoss** [comment]
That was me. ;)

Migrating to a new VPS is still on my todo list.

It's funny how the thing you write in a few hours for kicls actually gets
used, I'm surprised this has stayed up for as long as it has.

On Jul 7, 2017 12:39, "martnsh" <notifications@github.com> wrote:

Closed #8
<https://github.com/mrmoss/saltybet_tools_chrome_extension/issues/8>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrmoss/saltybet_tools_chrome_extension/issues/8#event-1155128314>,
or mute the thread

**Comment by martnsh** [comment]
Thanks for your quick work! Its a neat plugin :)
